filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
  # Or output.elasticsearch if you're not using Logstash
  # output.elasticsearch:
  #   hosts: ["elasticsearch:9200"]
